---
name: Publish to PyPI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-and-deploy:
    name: "Build and deploy to PyPI"
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Set up Python 3.8"
        uses: "actions/setup-python@v4"
        with:
          python-version: "3.8"

      - name: "Install Prereqs"
        run: "pip install --upgrade pip setuptools wheel"

      - name: "Install Build Requirements"
        run: "pip install -e .[build]"

      - name: "Build source distribution and wheel"
        run: "python -m build --sdist --wheel --outdir dist/ ."

      - name: "Publish to PyPI"
        uses: "pypa/gh-action-pypi-publish@release/v1"
        with:
          password: "${{ secrets.PYPI_API_TOKEN }}"
